"""Supplementary Marmas — remaining points to complete 107 total"""
from typing import Any

SUPPLEMENTARY_MARMAS: list[dict[str, Any]] = [
    {"id": "guda", "name": "Guda", "devanagari": "गुद", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Udara (Abdomen)", "zone": "Perineum / anorectal",
     "location": "Anorectal junction — perineal body",
     "modern_mapping": "Anal sphincter complex (internal + external); pudendal nerve and vessels; ischiorectal fossa; levator ani.",
     "size_anguli": 4, "tissue_type": "Mamsa + Sira",
     "consequences": "Sphincter destruction causes permanent faecal incontinence. Pudendal vessel injury causes deep pelvic haemorrhage.",
     "protective_doctrine": "In abdominoperineal resection, identify and protect pudendal nerve in Alcock's canal. In perineal repair, preserve external sphincter fibres.",
     "shloka": {"sanskrit": "गुदे विद्धे सद्यो मरणम्।", "transliteration": "Gude viddhe sadyo maraṇam.", "meaning": "Injury to Guda causes immediate death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.4"},
     "procedures_at_risk": ["APR", "Haemorrhoidectomy", "Anal fistula surgery", "Perineal repair"],
     "surgical_relevance": ["colorectal", "perineal"]},

    {"id": "parshvasandhi", "name": "Pārśvasandhi", "devanagari": "पार्श्वसन्धि", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Udara (Abdomen)", "zone": "Flank / costovertebral",
     "location": "Costovertebral angle — junction of 12th rib and spine",
     "modern_mapping": "Kidney (posterior surface); 12th rib; subcostal neurovascular bundle; quadratus lumborum; psoas major.",
     "size_anguli": 2, "tissue_type": "Snayu + Asthi",
     "consequences": "Injury causes renal damage, retroperitoneal haemorrhage, pneumothorax if pleura breached above 12th rib.",
     "protective_doctrine": "In loin incision for nephrectomy, count ribs carefully — incision above 12th rib risks pleural breach. Protect subcostal nerve.",
     "shloka": {"sanskrit": "पार्श्वसन्धौ विद्धे कुक्षिशूलं रक्तं च।", "transliteration": "Pārśvasandhau viddhe kukṣiśūlaṃ raktaṃ ca.", "meaning": "Injury to Parshvasandhi causes flank pain and bleeding.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.25"},
     "procedures_at_risk": ["Nephrectomy (open)", "Posterolateral thoracotomy", "Lumbar spine surgery"],
     "surgical_relevance": ["renal", "thoracic", "spine"]},

    {"id": "brihati", "name": "Bṛhatī", "devanagari": "बृहती", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Prishtha (Back)", "zone": "Scapular",
     "location": "Medial border of scapula — infrascapular region",
     "modern_mapping": "Dorsal scapular nerve and artery; rhomboid muscles; serratus anterior (posterior slip); thoracodorsal nerve; subscapular artery branches.",
     "size_anguli": 2, "tissue_type": "Mamsa + Sira",
     "consequences": "Thoracodorsal nerve injury causes latissimus dorsi paralysis. Subscapular artery injury causes deep haemorrhage.",
     "protective_doctrine": "In posterior axillary dissection and latissimus dorsi flap harvest, identify thoracodorsal pedicle before elevating muscle.",
     "shloka": {"sanskrit": "बृहत्यां विद्धे भुजबलक्षयः।", "transliteration": "Bṛhatyāṃ viddhe bhujabalakṣayaḥ.", "meaning": "Injury to Brihati causes loss of arm strength.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.25"},
     "procedures_at_risk": ["Latissimus dorsi flap", "Posterior thoracotomy", "Scapulectomy"],
     "surgical_relevance": ["plastic", "thoracic", "oncology"]},

    {"id": "amsa_phalaka", "name": "Aṃsaphalaka", "devanagari": "अंसफलक", "count": 2, "sides": "bilateral",
     "classification": "Vaikalyakara", "risk": "Moderate",
     "region": "Prishtha (Back)", "zone": "Scapula body",
     "location": "Body of scapula — infraspinous fossa",
     "modern_mapping": "Suprascapular nerve (at spinoglenoid notch); infraspinatus muscle; circumflex scapular artery; scapular spine.",
     "size_anguli": 4, "tissue_type": "Asthi + Mamsa",
     "consequences": "Suprascapular nerve injury causes infraspinatus/supraspinatus weakness — external rotation and abduction loss.",
     "protective_doctrine": "In posterior approach to shoulder, protect suprascapular nerve at spinoglenoid notch. In scapula fracture ORIF, identify neurovascular bundle.",
     "shloka": {"sanskrit": "अंसफलके विद्धे भुजवैकल्यम्।", "transliteration": "Aṃsaphalake viddhe bhujavaikaḷyam.", "meaning": "Injury to Amsaphalaka causes disability of the arm.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.26"},
     "procedures_at_risk": ["Shoulder arthroplasty (posterior)", "Scapula fracture ORIF", "Rotator cuff repair (open)"],
     "surgical_relevance": ["shoulder", "orthopaedic"]},
]
