"""Head & Neck Marmas — 37 points (Shiras + Greeva region)"""
from typing import Any

HEAD_NECK_MARMAS: list[dict[str, Any]] = [
    {"id": "adhipati", "name": "Adhipati", "devanagari": "अधिपति", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Shiras (Head)", "zone": "Vertex / bregma",
     "location": "Crown of the head — anterior fontanelle / bregma",
     "modern_mapping": "Superior sagittal sinus; bridging veins; falx cerebri; motor cortex (leg area). Bregma is junction of coronal and sagittal sutures.",
     "size_anguli": 1, "tissue_type": "Sandhi (suture)",
     "consequences": "Superior sagittal sinus injury causes massive venous haemorrhage and air embolism. Falx injury causes bilateral leg weakness.",
     "protective_doctrine": "In craniotomy near midline, identify and protect superior sagittal sinus. Never cross midline without imaging confirmation of sinus position.",
     "shloka": {"sanskrit": "अधिपतौ विद्धे सद्यो मरणम्।", "transliteration": "Adhipatau viddhe sadyo maraṇam.", "meaning": "Injury to Adhipati causes immediate death — the supreme Marma of the head.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.3"},
     "procedures_at_risk": ["Craniotomy", "VP shunt insertion", "Parasagittal meningioma excision"],
     "surgical_relevance": ["neurosurgery", "cranial"]},

    {"id": "simanta", "name": "Sīmanta", "devanagari": "सीमन्त", "count": 5,
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Shiras (Head)", "zone": "Cranial sutures",
     "location": "Five cranial suture lines — coronal, sagittal, lambdoid, squamous (bilateral)",
     "modern_mapping": "Cranial suture junctions; dural venous sinuses at confluence; meningeal arteries crossing suture lines; diploeic veins.",
     "size_anguli": 4, "tissue_type": "Sandhi (suture) + Asthi",
     "consequences": "Suture diastasis in trauma causes dural tears and CSF leak. Middle meningeal artery injury at pterion causes epidural haematoma.",
     "protective_doctrine": "Pterion (junction of frontal, parietal, temporal, sphenoid) is the thinnest skull area and overlies middle meningeal artery. Always burr here with caution.",
     "shloka": {"sanskrit": "सीमन्ते विद्धे कालान्तरे मरणम्।", "transliteration": "Sīmante viddhe kālāntare maraṇam.", "meaning": "Injury to Simanta causes death over time — reflecting delayed intracranial haemorrhage.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.20"},
     "procedures_at_risk": ["Craniotomy", "Cranioplasty", "Epidural haematoma evacuation"],
     "surgical_relevance": ["neurosurgery", "trauma"]},

    {"id": "sthapani", "name": "Sthāpanī", "devanagari": "स्थापनी", "count": 1,
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Shiras (Head)", "zone": "Glabella / nasion",
     "location": "Glabella — between the eyebrows (the 'third eye' point)",
     "modern_mapping": "Frontal sinus; supratrochlear and supraorbital neurovascular bundles; anterior ethmoidal artery; frontal bone.",
     "size_anguli": 1, "tissue_type": "Sira + Asthi",
     "consequences": "Frontal sinus fracture causes CSF rhinorrhoea. Anterior ethmoidal artery injury causes orbital haematoma.",
     "protective_doctrine": "In FESS (endoscopic sinus surgery), identify anterior ethmoidal artery at skull base — its injury causes retro-orbital haematoma and blindness.",
     "shloka": {"sanskrit": "स्थापन्यां विद्धे दृष्टिनाशः कालान्तरे च मृत्युः।", "transliteration": "Sthāpanyāṃ viddhe dṛṣṭināśaḥ kālāntare ca mṛtyuḥ.", "meaning": "Injury to Sthapani causes vision loss and eventual death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.22"},
     "procedures_at_risk": ["FESS", "Frontal craniotomy", "Rhinoplasty", "Orbital surgery"],
     "surgical_relevance": ["ent", "neurosurgery", "ophthalmology"]},

    {"id": "shankha", "name": "Śaṅkha", "devanagari": "शङ्ख", "count": 2, "sides": "bilateral",
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Shiras (Head)", "zone": "Temple / pterion",
     "location": "Temple — pterion region (thinnest skull area)",
     "modern_mapping": "Middle meningeal artery; temporal bone (thinnest); temporal lobe; Sylvian fissure; middle cerebral artery territory.",
     "size_anguli": 2, "tissue_type": "Asthi + Sira",
     "consequences": "Middle meningeal artery rupture causes epidural haematoma — the 'talk and die' injury. Lucid interval followed by rapid deterioration.",
     "protective_doctrine": "Temporal region is the most vulnerable skull area. Any trauma here mandates urgent CT. In craniotomy, identify MMA and cauterize before lifting bone flap.",
     "shloka": {"sanskrit": "शङ्खे विद्धे सद्यो मरणम्।", "transliteration": "Śaṅkhe viddhe sadyo maraṇam.", "meaning": "Injury to Shankha (temple) causes immediate death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.3"},
     "procedures_at_risk": ["Pterional craniotomy", "Temporal lobectomy", "Epidural haematoma evacuation"],
     "surgical_relevance": ["neurosurgery", "trauma"]},

    {"id": "utkshepa", "name": "Utkṣepa", "devanagari": "उत्क्षेप", "count": 2, "sides": "bilateral",
     "classification": "Vishalyaghna", "risk": "Critical",
     "region": "Shiras (Head)", "zone": "Temporal (superior)",
     "location": "Superior to Shankha — above the ear at the temporal ridge",
     "modern_mapping": "Superior temporal line; temporal branch of superficial temporal artery; temporal branch of facial nerve (VII); temporalis muscle.",
     "size_anguli": 2, "tissue_type": "Sira + Snayu",
     "consequences": "Vishalyaghna: the foreign body keeps the patient alive — removal causes death. Modern: retained bone fragment tamponading a dural sinus tear.",
     "protective_doctrine": "In penetrating cranial injury, do NOT remove embedded objects without surgical preparation — they may be tamponading a sinus. Remove only in OR with haemorrhage control.",
     "shloka": {"sanskrit": "उत्क्षेपे शल्यमाश्रिते जीवति विशल्ये म्रियते।", "transliteration": "Utkṣepe śalyamāśrite jīvati viśalye mriyate.", "meaning": "In Utkṣepa — the patient lives with the foreign body but dies on its removal.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.8"},
     "procedures_at_risk": ["Penetrating cranial injury", "Temporal craniotomy"],
     "surgical_relevance": ["neurosurgery", "trauma"]},

    {"id": "avarta", "name": "Āvarta", "devanagari": "आवर्त", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Shiras (Head)", "zone": "Supra-orbital",
     "location": "Supra-orbital notch / foramen region — above each eye",
     "modern_mapping": "Supraorbital nerve and artery; frontal sinus; orbital roof; levator palpebrae superioris; trochlear nerve (IV).",
     "size_anguli": 1, "tissue_type": "Sira + Sandhi",
     "consequences": "Supraorbital nerve damage causes forehead anaesthesia. Orbital roof fracture causes CSF leak and brain herniation.",
     "protective_doctrine": "In brow lift and forehead flap surgery, identify and preserve supraorbital nerve at the notch/foramen. It emerges 2.5cm from midline.",
     "shloka": {"sanskrit": "आवर्ते विद्धे अन्धत्वं कालान्तरे च मृत्युः।", "transliteration": "Āvarte viddhe andhartvaṃ kālāntare ca mṛtyuḥ.", "meaning": "Injury to Avarta causes blindness and eventual death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.22"},
     "procedures_at_risk": ["Brow lift", "Frontal craniotomy", "Orbital decompression"],
     "surgical_relevance": ["plastic", "neurosurgery", "ophthalmology"]},

    {"id": "apanga", "name": "Apāṅga", "devanagari": "अपाङ्ग", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Shiras (Head)", "zone": "Lateral orbit / lateral canthus",
     "location": "Lateral corner of the eye — lateral canthus",
     "modern_mapping": "Lacrimal gland; lateral rectus muscle; zygomaticotemporal nerve; lateral orbital wall; zygomatic branch of facial nerve.",
     "size_anguli": 1, "tissue_type": "Sira + Snayu",
     "consequences": "Lacrimal gland injury causes dry eye. Lateral rectus damage causes diplopia. Facial nerve zygomatic branch injury causes inability to close eye.",
     "protective_doctrine": "In lateral orbitotomy, identify lacrimal gland and lateral rectus before retraction. Protect zygomatic branch of facial nerve in facelift temporal dissection.",
     "shloka": {"sanskrit": "अपाङ्गे विद्धे दृष्टिनाशो भवति।", "transliteration": "Apāṅge viddhe dṛṣṭināśo bhavati.", "meaning": "Injury to Apanga causes loss of vision.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.22"},
     "procedures_at_risk": ["Lateral orbitotomy", "Zygoma fracture ORIF", "Facelift (temporal)"],
     "surgical_relevance": ["ophthalmology", "maxillofacial", "plastic"]},

    {"id": "shringataka", "name": "Śṛṅgāṭaka", "devanagari": "शृङ्गाटक", "count": 4,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Shiras (Head)", "zone": "Skull base / cavernous sinus",
     "location": "Junction point where nasal, oral, aural, and ophthalmic channels converge — corresponds to skull base central region",
     "modern_mapping": "Cavernous sinus; internal carotid artery (cavernous segment); cranial nerves III, IV, V1, V2, VI in cavernous sinus wall; sphenoid sinus; sella turcica (pituitary).",
     "size_anguli": 4, "tissue_type": "Sira",
     "consequences": "Cavernous sinus injury causes carotid-cavernous fistula, cranial nerve palsies, and uncontrollable haemorrhage. Sella injury damages pituitary.",
     "protective_doctrine": "In trans-sphenoidal pituitary surgery, stay midline. Lateral deviation risks cavernous sinus entry and internal carotid artery injury — catastrophic.",
     "shloka": {"sanskrit": "शृङ्गाटके विद्धे सद्यो मरणम्।", "transliteration": "Śṛṅgāṭake viddhe sadyo maraṇam.", "meaning": "Injury to Shringataka causes immediate death — the confluence of vital channels.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.3"},
     "procedures_at_risk": ["Trans-sphenoidal pituitary surgery", "Skull base surgery", "FESS (posterior)"],
     "surgical_relevance": ["neurosurgery", "ent", "skull_base"]},

    {"id": "vidhura", "name": "Vidhura", "devanagari": "विधुर", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Shiras (Head)", "zone": "Mastoid / post-auricular",
     "location": "Behind the ear — mastoid process region",
     "modern_mapping": "Mastoid bone; facial nerve (VII) at stylomastoid foramen; sigmoid sinus; posterior auricular artery; mastoid air cells.",
     "size_anguli": 1, "tissue_type": "Snayu + Sira",
     "consequences": "Facial nerve injury at stylomastoid foramen causes complete ipsilateral facial paralysis. Sigmoid sinus injury causes venous haemorrhage and air embolism.",
     "protective_doctrine": "In mastoidectomy, facial nerve runs in the fallopian canal — identify using Bill's bar (lateral semicircular canal) as landmark. Nerve monitor essential.",
     "shloka": {"sanskrit": "विधुरे विद्धे बाधिर्यं कालान्तरे मृत्युः।", "transliteration": "Vidhure viddhe bādhiryaṃ kālāntare mṛtyuḥ.", "meaning": "Injury to Vidhura causes deafness and eventual death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.21"},
     "procedures_at_risk": ["Mastoidectomy", "Parotidectomy", "Cochlear implant", "Retrosigmoid craniotomy"],
     "surgical_relevance": ["ent", "neurosurgery", "otology"]},

    {"id": "phana", "name": "Phana", "devanagari": "फन", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Shiras (Head)", "zone": "Nasal ala",
     "location": "Wings of the nose — nasal ala",
     "modern_mapping": "Lateral nasal artery (branch of facial artery); nasal branch of anterior ethmoidal nerve; nasalis muscle; nasal valve.",
     "size_anguli": 1, "tissue_type": "Sira",
     "consequences": "Injury causes loss of smell (anosmia), nasal valve collapse, and nasal airway obstruction.",
     "protective_doctrine": "In rhinoplasty, preserve lateral nasal artery for flap vascularity. Do not over-resect lower lateral cartilages — causes nasal valve collapse.",
     "shloka": {"sanskrit": "फने विद्धे घ्राणनाशः।", "transliteration": "Phane viddhe ghrāṇanāśaḥ.", "meaning": "Injury to Phana causes loss of smell.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.22"},
     "procedures_at_risk": ["Rhinoplasty", "Septoplasty", "Nasal fracture reduction"],
     "surgical_relevance": ["ent", "plastic"]},

    {"id": "krikatika", "name": "Kṛkāṭikā", "devanagari": "कृकाटिका", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Greeva (Neck)", "zone": "Atlanto-occipital",
     "location": "Junction of skull and cervical spine — occiput-C1 joint",
     "modern_mapping": "Atlanto-occipital joint; vertebral artery (V3 segment — loops around C1); C1 nerve root; medulla oblongata; brainstem.",
     "size_anguli": 1, "tissue_type": "Sandhi + Sira",
     "consequences": "Vertebral artery injury causes posterior circulation stroke. Atlanto-occipital dislocation is immediately fatal. Medullary injury causes respiratory arrest.",
     "protective_doctrine": "In C1-C2 fixation, vertebral artery is at extreme risk — runs in groove on C1 arch. Never place screws >15mm into C1 lateral mass without imaging.",
     "shloka": {"sanskrit": "कृकाटिकायां विद्धे शिरोग्रीवा स्तभ्यते मृत्युश्च।", "transliteration": "Kṛkāṭikāyāṃ viddhe śirogrīvā stabhyate mṛtyuśca.", "meaning": "Injury to Krikatika causes head/neck rigidity and death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.21"},
     "procedures_at_risk": ["C1-C2 fixation", "Posterior fossa craniotomy", "Odontoid screw fixation"],
     "surgical_relevance": ["spine", "neurosurgery"]},

    {"id": "manya", "name": "Manyā", "devanagari": "मन्या", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "Critical",
     "region": "Greeva (Neck)", "zone": "Carotid triangle",
     "location": "Lateral neck — carotid triangle (anterior to sternocleidomastoid)",
     "modern_mapping": "Common carotid artery; internal and external carotid arteries at bifurcation; carotid body (baroreceptor); internal jugular vein; vagus nerve (X); hypoglossal nerve (XII).",
     "size_anguli": 4, "tissue_type": "Sira + Dhamani (artery)",
     "consequences": "Carotid artery injury causes stroke and death. Vagus nerve injury causes vocal cord paralysis. Carotid body manipulation causes reflex bradycardia.",
     "protective_doctrine": "In carotid endarterectomy, avoid touching carotid body directly — causes dangerous bradycardia. Identify hypoglossal nerve crossing external carotid. Shunt if cross-clamp time > 3 min.",
     "shloka": {"sanskrit": "मन्यायां विद्धे वाक्स्वरनाशः कालान्तरे मृत्युः।", "transliteration": "Manyāyāṃ viddhe vāksvaranāśaḥ kālāntare mṛtyuḥ.", "meaning": "Injury to Manya causes loss of voice and eventual death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.21"},
     "procedures_at_risk": ["Carotid endarterectomy", "Radical neck dissection", "Thyroidectomy", "Anterior cervical discectomy"],
     "surgical_relevance": ["vascular", "ent", "oncology", "spine"]},

    {"id": "nila", "name": "Nīlā", "devanagari": "नीला", "count": 2, "sides": "bilateral",
     "classification": "Kalantara Pranahara", "risk": "High",
     "region": "Greeva (Neck)", "zone": "Anterior neck / larynx",
     "location": "Lateral to thyroid cartilage — alongside the larynx",
     "modern_mapping": "Superior laryngeal nerve (external branch); superior thyroid artery; thyroid gland lateral lobe; recurrent laryngeal nerve in tracheo-esophageal groove.",
     "size_anguli": 4, "tissue_type": "Sira + Dhamani",
     "consequences": "External SLN injury causes voice pitch change. RLN injury causes vocal cord paralysis (hoarseness/aspiration). Bilateral RLN injury causes airway obstruction.",
     "protective_doctrine": "In thyroidectomy: identify external branch of SLN (Cernea classification) before ligating superior thyroid artery. Find RLN at Berry's ligament or tracheo-esophageal groove using nerve monitor.",
     "shloka": {"sanskrit": "नीलायां विद्धे स्वरभङ्गः।", "transliteration": "Nīlāyāṃ viddhe svarabhaṅgaḥ.", "meaning": "Injury to Nila causes hoarseness — loss of voice quality.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.21"},
     "procedures_at_risk": ["Thyroidectomy", "Parathyroidectomy", "Anterior cervical spine surgery", "Laryngeal surgery"],
     "surgical_relevance": ["ent", "endocrine", "spine"]},

    {"id": "sira_matrika", "name": "Sirāmātṛkā", "devanagari": "सिरामातृका", "count": 8,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Greeva (Neck)", "zone": "Cervical vessels",
     "location": "Four vessels on each side of the neck — total 8 'mother vessels'",
     "modern_mapping": "Internal and external carotid arteries; internal and external jugular veins; vertebral arteries — the 8 major cervical vessels that supply/drain the brain.",
     "size_anguli": 4, "tissue_type": "Sira + Dhamani",
     "consequences": "Injury to any of these 8 vessels causes cerebral ischaemia, air embolism, or exsanguination. They are called 'Matrika' (mothers) because they nourish the brain.",
     "protective_doctrine": "All neck surgery requires awareness of these 8 vessels. In radical neck dissection, preserve at least one internal jugular vein for cerebral venous drainage.",
     "shloka": {"sanskrit": "सिरामातृकासु विद्धासु सद्यो मरणम्।", "transliteration": "Sirāmātṛkāsu viddhāsu sadyo maraṇam.", "meaning": "Injury to Siramatrika (the mother vessels) causes immediate death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.3; Aṣṭāṅgahṛdayam, Śārīrasthāna 4.37"},
     "procedures_at_risk": ["Radical neck dissection", "Carotid surgery", "Anterior cervical spine surgery", "Tracheostomy"],
     "surgical_relevance": ["vascular", "ent", "oncology", "spine"]},
]
