"""Trunk Marmas — Udara (abdomen), Uras (chest), Prishtha (back) — 12 points"""
from typing import Any

TRUNK_MARMAS: list[dict[str, Any]] = [
    {"id": "nabhi", "name": "Nābhi", "devanagari": "नाभि", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Udara (Abdomen)", "zone": "Umbilical",
     "location": "Umbilical region — periumbilical area",
     "modern_mapping": "Abdominal aortic bifurcation; inferior mesenteric artery; autonomic plexuses (coeliac/mesenteric territory).",
     "size_anguli": 4, "tissue_type": "Sira",
     "consequences": "Immediate haemodynamic collapse. Aortic/IMA injury is rapidly fatal.",
     "protective_doctrine": "Maintain depth awareness during umbilical port insertion. Great vessels lie centimetres behind peritoneum.",
     "shloka": {"sanskrit": "नाभ्यां विद्धे सद्यः प्राणान् जहाति।", "transliteration": "Nābhyāṃ viddhe sadyaḥ prāṇān jahāti.", "meaning": "Injury to Nabhi causes immediate loss of life.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.16"},
     "procedures_at_risk": ["Laparoscopic Cholecystectomy", "Appendectomy", "Umbilical hernia repair"],
     "surgical_relevance": ["laparoscopic", "open_abdominal"]},

    {"id": "hridaya", "name": "Hṛdaya", "devanagari": "हृदय", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Uras (Thorax)", "zone": "Precordium",
     "location": "Cardiac region — precordium",
     "modern_mapping": "Heart, pericardium, coronary arteries, cardiac conduction system, great vessel origins.",
     "size_anguli": 4, "tissue_type": "Sira + Mamsa",
     "consequences": "Immediate cardiac arrest and death.",
     "protective_doctrine": "In thoracic procedures, maintain awareness of cardiac silhouette. Mediastinal dissection requires careful landmark identification.",
     "shloka": {"sanskrit": "हृदयं चेत् विद्धं सद्यो मरणम्।", "transliteration": "Hṛdayaṃ cet viddhaṃ sadyo maraṇam.", "meaning": "If the heart Marma is injured, death follows immediately.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.3"},
     "procedures_at_risk": ["CABG", "Thoracotomy", "Mediastinoscopy", "Pericardiocentesis"],
     "surgical_relevance": ["cardiothoracic", "thoracoscopic"]},

    {"id": "stanamula_r", "name": "Stanamūla (Right)", "devanagari": "स्तनमूल (दक्षिण)", "count": 2, "sides": "bilateral",
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Uras (Thorax)", "zone": "Infra-mammary",
     "location": "Root of the breast — infra-mammary fold region",
     "modern_mapping": "Internal mammary artery (IMA); intercostal neurovascular bundles (4th-6th); lung apex; cardiac margin (left side).",
     "size_anguli": 2, "tissue_type": "Sira + Mamsa",
     "consequences": "IMA injury causes massive intra-thoracic haemorrhage. Intercostal artery injury is difficult to control.",
     "protective_doctrine": "In mastectomy and chest tube insertion, identify IMA (runs 1cm lateral to sternum). Insert chest tubes above the rib to avoid neurovascular bundle.",
     "shloka": {"sanskrit": "स्तनमूले विद्धे श्वासो रुद्ध्यति मृत्युश्च।", "transliteration": "Stanamūle viddhe śvāso ruddhyati mṛtyuśca.", "meaning": "Injury to Stanamula obstructs breathing and causes death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.17"},
     "procedures_at_risk": ["Mastectomy", "Chest tube insertion", "CABG (IMA harvest)", "Thoracotomy"],
     "surgical_relevance": ["breast", "cardiothoracic"]},

    {"id": "stanarohita", "name": "Stanarohita", "devanagari": "स्तनरोहित", "count": 2, "sides": "bilateral",
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Uras (Thorax)", "zone": "Supra-mammary / pectoral",
     "location": "2 anguli above the nipple — upper breast / pectoral region",
     "modern_mapping": "Pectoralis major and minor muscles; thoracoacromial artery; lateral pectoral nerve; axillary lymphatic drainage.",
     "size_anguli": 2, "tissue_type": "Sira + Mamsa",
     "consequences": "Injury causes pectoral muscle denervation, lymphatic disruption, haemorrhage from thoracoacromial trunk.",
     "protective_doctrine": "In axillary dissection for breast cancer, identify and preserve lateral pectoral nerve to maintain pectoralis major function.",
     "shloka": {"sanskrit": "स्तनरोहिते विद्धे रक्तं स्रवति प्राणाश्च।", "transliteration": "Stanarohite viddhe raktaṃ sravati prāṇāśca.", "meaning": "Injury to Stanarohita causes bleeding and loss of vitality.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.18"},
     "procedures_at_risk": ["Modified radical mastectomy", "Axillary dissection", "Pectoralis flap harvest"],
     "surgical_relevance": ["breast", "oncology", "plastic"]},

    {"id": "apalapa", "name": "Apalāpa", "devanagari": "अपलाप", "count": 2, "sides": "bilateral",
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Uras (Thorax)", "zone": "Axillary",
     "location": "Lateral chest wall at axillary line",
     "modern_mapping": "Lateral thoracic artery; long thoracic nerve (nerve of Bell); serratus anterior muscle; intercostobrachial nerve.",
     "size_anguli": 1, "tissue_type": "Sira",
     "consequences": "Long thoracic nerve injury causes winged scapula. Lateral thoracic artery haemorrhage.",
     "protective_doctrine": "In axillary dissection, identify long thoracic nerve running on serratus anterior — it is the most commonly injured nerve in breast surgery.",
     "shloka": {"sanskrit": "अपलापे विद्धे बाहुर्गतिहीनः।", "transliteration": "Apalāpe viddhe bāhurgatihīnaḥ.", "meaning": "Injury to Apalapa causes loss of arm movement (winged scapula).", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.19"},
     "procedures_at_risk": ["ALND", "Lateral thoracotomy", "Chest wall resection"],
     "surgical_relevance": ["breast", "oncology", "thoracic"]},

    {"id": "basti", "name": "Basti", "devanagari": "बस्ति", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Udara (Abdomen)", "zone": "Hypogastric / pelvic",
     "location": "Hypogastric region — bladder and pelvic floor",
     "modern_mapping": "Urinary bladder; iliac vessels; in females — uterine arteries and broad ligament; ureters; obturator nerve.",
     "size_anguli": 4, "tissue_type": "Sira + Mamsa",
     "consequences": "Iliac vessel haemorrhage; bladder perforation causes peritonitis; ureteric injury causes hydronephrosis.",
     "protective_doctrine": "Decompress bladder before lower abdominal surgery. Identify ureters bilaterally in pelvic procedures. In TAPP/TEP, avoid triangle of doom (vas + vessels).",
     "shloka": {"sanskrit": "बस्तौ विद्धे मूत्रं स्रवति प्राणाश्च क्षीयन्ते।", "transliteration": "Bastau viddhe mūtraṃ sravati prāṇāśca kṣīyante.", "meaning": "Injury to Basti causes urinary leak and gradual loss of life.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.28"},
     "procedures_at_risk": ["Hysterectomy", "Cystectomy", "Colectomy", "TAPP/TEP hernioplasty"],
     "surgical_relevance": ["pelvic", "gynaecological", "urological"]},

    {"id": "yakrt", "name": "Yakṛt", "devanagari": "यकृत्", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Udara (Abdomen)", "zone": "Right hypochondrium",
     "location": "Right hypochondrium — hepatic region",
     "modern_mapping": "Liver parenchyma; hepatic hilum (portal triad: portal vein, hepatic artery, bile duct); Glisson's capsule; hepatic veins.",
     "size_anguli": 4, "tissue_type": "Sira + Mamsa",
     "consequences": "Uncontrolled hepatic haemorrhage. Portal vein injury rapidly fatal. Bile duct injury causes long-term morbidity.",
     "protective_doctrine": "During liver bed dissection, maintain shallow plane. Identify Rouviere's sulcus as safety landmark. Pringle manoeuvre for haemorrhage control.",
     "shloka": {"sanskrit": "यकृत्प्लीहनोः प्रहारे रक्तं स्रवति मृत्युश्च।", "transliteration": "Yakṛtplīhanoḥ prahāre raktaṃ sravati mṛtyuśca.", "meaning": "Injury to liver and spleen causes haemorrhage and death.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.23"},
     "procedures_at_risk": ["Cholecystectomy", "Liver resection", "Whipple procedure", "Trauma laparotomy"],
     "surgical_relevance": ["hepatobiliary", "laparoscopic"]},

    {"id": "pleeha", "name": "Plīhā", "devanagari": "प्लीहा", "count": 1,
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Udara (Abdomen)", "zone": "Left hypochondrium",
     "location": "Left hypochondrium — splenic region",
     "modern_mapping": "Spleen; splenic hilum (splenic artery and vein); tail of pancreas; left colic flexure.",
     "size_anguli": 4, "tissue_type": "Sira + Mamsa",
     "consequences": "Splenic rupture causes catastrophic intraperitoneal haemorrhage. Splenic artery is largest branch of coeliac trunk.",
     "protective_doctrine": "Avoid excessive traction on splenocolic ligament. In splenectomy, ligate splenic artery first. In left colectomy, stay away from splenic flexure attachments.",
     "shloka": {"sanskrit": "प्लीहनि विद्धे रक्तं बहु स्रवति।", "transliteration": "Plīhani viddhe raktaṃ bahu sravati.", "meaning": "Injury to the spleen causes profuse bleeding.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.23"},
     "procedures_at_risk": ["Splenectomy", "Left colectomy", "Distal pancreatectomy", "Gastric surgery"],
     "surgical_relevance": ["abdominal", "laparoscopic"]},

    {"id": "vrukka", "name": "Vṛkka", "devanagari": "वृक्क", "count": 2, "sides": "bilateral",
     "classification": "Sadya Pranahara", "risk": "Critical",
     "region": "Prishtha (Back)", "zone": "Renal / lumbar",
     "location": "Lumbar region — flanks bilaterally (corresponding to kidneys)",
     "modern_mapping": "Kidneys; renal artery and vein; adrenal glands; renal pelvis; retroperitoneal fat.",
     "size_anguli": 4, "tissue_type": "Sira + Mamsa",
     "consequences": "Renal artery injury causes massive retroperitoneal haemorrhage. Renal vein injury difficult to control.",
     "protective_doctrine": "In nephrectomy, ligate renal artery before vein. In retroperitoneal access for spine surgery, identify and retract ureter.",
     "shloka": {"sanskrit": "वृक्के विद्धे मूत्रं रक्तमिश्रं स्रवति।", "transliteration": "Vṛkke viddhe mūtraṃ raktamiśraṃ sravati.", "meaning": "Injury to the kidney causes blood-mixed urine (haematuria).", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.24"},
     "procedures_at_risk": ["Nephrectomy", "PCNL", "Adrenalectomy", "Lumbar spine surgery"],
     "surgical_relevance": ["renal", "urological", "spine"]},

    {"id": "katikatarunaa", "name": "Kaṭīkatāruṇa", "devanagari": "कटीकतरुण", "count": 2, "sides": "bilateral",
     "classification": "Vaikalyakara", "risk": "Moderate",
     "region": "Prishtha (Back)", "zone": "Sacroiliac",
     "location": "Sacroiliac joint region",
     "modern_mapping": "Sacroiliac joint; sacral nerve roots (S1-S3); superior gluteal artery; piriformis muscle.",
     "size_anguli": 2, "tissue_type": "Asthi + Snayu",
     "consequences": "SI joint disruption causes pelvic instability. Superior gluteal artery injury causes deep pelvic haemorrhage. Sacral nerve root injury causes bladder/bowel dysfunction.",
     "protective_doctrine": "In posterior approach to pelvis, identify piriformis and protect superior gluteal artery above it. Sacral screw placement requires fluoroscopy.",
     "shloka": {"sanskrit": "कटीकतरुणे विद्धे शकृन्मूत्रप्रवृत्तिः।", "transliteration": "Kaṭīkatāruṇe viddhe śakṛnmūtrapravṛttiḥ.", "meaning": "Injury causes incontinence of stool and urine (sacral nerve damage).", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.25"},
     "procedures_at_risk": ["SI joint fusion", "Pelvic fracture ORIF", "Sacrectomy"],
     "surgical_relevance": ["pelvis", "spine", "orthopaedic"]},

    {"id": "kukundara", "name": "Kukundara", "devanagari": "कुकुन्दर", "count": 2, "sides": "bilateral",
     "classification": "Vaikalyakara", "risk": "Moderate",
     "region": "Prishtha (Back)", "zone": "Gluteal / sciatic",
     "location": "Deep gluteal region — sciatic notch area",
     "modern_mapping": "Sciatic nerve at greater sciatic notch; inferior gluteal artery; pudendal nerve and vessels; piriformis muscle.",
     "size_anguli": 2, "tissue_type": "Snayu + Sira",
     "consequences": "Sciatic nerve injury causes foot drop and loss of sensation below knee. Inferior gluteal artery injury causes deep haemorrhage.",
     "protective_doctrine": "In posterior hip approach (Moore/Southern), identify and protect sciatic nerve behind short external rotators. It exits below piriformis.",
     "shloka": {"sanskrit": "कुकुन्दरे विद्धे पादौ शिथिलौ भवतः।", "transliteration": "Kukundare viddhe pādau śithilau bhavataḥ.", "meaning": "Injury to Kukundara causes both legs to become flaccid (sciatic palsy).", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.26"},
     "procedures_at_risk": ["Total hip arthroplasty (posterior)", "Sciatic nerve repair", "Gluteal abscess drainage"],
     "surgical_relevance": ["hip", "orthopaedic", "neurosurgery"]},

    {"id": "nitamba", "name": "Nitamba", "devanagari": "नितम्ब", "count": 2, "sides": "bilateral",
     "classification": "Vaikalyakara", "risk": "Moderate",
     "region": "Prishtha (Back)", "zone": "Iliac crest / hip",
     "location": "Iliac crest and greater trochanter region",
     "modern_mapping": "Iliac crest; gluteus medius and minimus (hip abductors); superior gluteal nerve; lateral femoral cutaneous nerve.",
     "size_anguli": 4, "tissue_type": "Asthi + Mamsa",
     "consequences": "Superior gluteal nerve injury causes Trendelenburg gait (hip abductor paralysis). Lateral femoral cutaneous nerve damage causes meralgia paraesthetica.",
     "protective_doctrine": "In lateral approach to hip, split gluteus medius no more than 5cm above greater trochanter to protect superior gluteal nerve.",
     "shloka": {"sanskrit": "नितम्बे विद्धे गतिवैकल्यम्।", "transliteration": "Nitambe viddhe gativaikalyam.", "meaning": "Injury to Nitamba causes gait abnormality.", "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.26"},
     "procedures_at_risk": ["Hip arthroplasty (lateral approach)", "Iliac crest bone graft harvest", "Pelvic osteotomy"],
     "surgical_relevance": ["hip", "orthopaedic"]},
]
