"""Upper limb Marmas — 22 points (11 per side x 2)"""
from typing import Any

UPPER_LIMB_MARMAS: list[dict[str, Any]] = [
    {
        "id": "talahridaya_hand",
        "name": "Talahṛdaya (Hand)",
        "devanagari": "तलहृदय (हस्त)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "Moderate",
        "region": "Shakha (Upper Limb)",
        "zone": "Palm",
        "location": "Centre of the palm (talahridaya = heart of the palm)",
        "modern_mapping": "Superficial palmar arch; median and ulnar nerve terminal branches; flexor digitorum superficialis tendons. Corresponds to the central palmar space.",
        "size_anguli": 1,
        "tissue_type": "Sira (vessel) + Mamsa (muscle)",
        "consequences": "Injury causes loss of grip, flexor tendon damage, palmar arch haemorrhage, and functional impairment of all fingers.",
        "protective_doctrine": "Avoid deep dissection in palmar centre during hand surgery. Use tourniquet and loupe magnification.",
        "shloka": {
            "sanskrit": "तलहृदये विद्धे करः शुष्यति।",
            "transliteration": "Talahṛdaye viddhe karaḥ śuṣyati.",
            "meaning": "When Talahridaya is injured, the hand becomes withered/non-functional.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.27",
        },
        "procedures_at_risk": ["Palmar fasciectomy", "Carpal tunnel release", "Flexor tendon repair"],
        "surgical_relevance": ["hand", "orthopaedic"],
    },
    {
        "id": "kshipra_hand",
        "name": "Kṣipra (Hand)",
        "devanagari": "क्षिप्र (हस्त)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Sadya Pranahara",
        "risk": "Critical",
        "region": "Shakha (Upper Limb)",
        "zone": "Web space thumb-index",
        "location": "Web space between thumb and index finger (first dorsal interosseous space)",
        "modern_mapping": "First dorsal interosseous muscle; radial artery entering deep palmar arch; median nerve digital branch. Deep pressure here can arrest hand circulation.",
        "size_anguli": 1,
        "tissue_type": "Sira + Snayu (ligament)",
        "consequences": "Injury to radial artery here causes ischaemia of thumb and index finger. Nerve injury causes thenar weakness.",
        "protective_doctrine": "Avoid clamping or blind suturing in the first web space. Identify radial artery before any dissection.",
        "shloka": {
            "sanskrit": "क्षिप्रे विद्धे मरणं सद्यो भवति।",
            "transliteration": "Kṣipre viddhe maraṇaṃ sadyo bhavati.",
            "meaning": "Injury to Kshipra causes immediate death — indicating the critical nature of vascular structures here.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.15",
        },
        "procedures_at_risk": ["Adductor pollicis release", "De Quervain's surgery", "Thumb reconstruction"],
        "surgical_relevance": ["hand", "vascular", "orthopaedic"],
    },
    {
        "id": "kurcha_hand",
        "name": "Kurca (Hand)",
        "devanagari": "कूर्च (हस्त)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Rujakara",
        "risk": "Low",
        "region": "Shakha (Upper Limb)",
        "zone": "Thenar eminence",
        "location": "Thenar eminence at the base of the thumb",
        "modern_mapping": "Thenar muscles (abductor pollicis brevis, opponens pollicis, flexor pollicis brevis); recurrent branch of median nerve.",
        "size_anguli": 4,
        "tissue_type": "Mamsa (muscle)",
        "consequences": "Injury causes severe pain and loss of thumb opposition — functional loss of pinch grip.",
        "protective_doctrine": "The recurrent motor branch of median nerve exits at the distal edge of flexor retinaculum — do not cut laterally during carpal tunnel release.",
        "shloka": {
            "sanskrit": "कूर्चे विद्धे वेदना भवति तीव्रा।",
            "transliteration": "Kūrce viddhe vedanā bhavati tīvrā.",
            "meaning": "Injury to Kurca causes intense pain.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.32",
        },
        "procedures_at_risk": ["Carpal tunnel release", "Thenar flap harvest", "CMC joint arthroplasty"],
        "surgical_relevance": ["hand", "orthopaedic"],
    },
    {
        "id": "kurchashira_hand",
        "name": "Kūrcaśira (Hand)",
        "devanagari": "कूर्चशिर (हस्त)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "Moderate",
        "region": "Shakha (Upper Limb)",
        "zone": "Radial wrist",
        "location": "Radial side of wrist at the base of thenar eminence (anatomical snuffbox region)",
        "modern_mapping": "Radial artery at the wrist; scaphoid bone; branches of radial nerve (superficial branch). Corresponds to anatomical snuffbox.",
        "size_anguli": 2,
        "tissue_type": "Snayu + Asthi (bone)",
        "consequences": "Injury causes wrist instability, radial artery damage, scaphoid fracture complications.",
        "protective_doctrine": "Radial artery cannulation site — use careful technique. Scaphoid fractures missed here lead to avascular necrosis.",
        "shloka": {
            "sanskrit": "कूर्चशिरसि विद्धे हस्तो वैकल्यं याति।",
            "transliteration": "Kūrcaśirasi viddhe hasto vaikalyaṃ yāti.",
            "meaning": "Injury to Kurchashira causes disability of the hand.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29",
        },
        "procedures_at_risk": ["Radial artery cannulation", "Scaphoid fixation", "Wrist arthroscopy"],
        "surgical_relevance": ["hand", "vascular", "orthopaedic"],
    },
    {
        "id": "manibandha",
        "name": "Maṇibandha",
        "devanagari": "मणिबन्ध",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "Moderate",
        "region": "Shakha (Upper Limb)",
        "zone": "Wrist joint",
        "location": "Wrist joint (mani = wrist, bandha = joint)",
        "modern_mapping": "Radiocarpal joint; flexor and extensor tendons; median nerve at carpal tunnel; radial and ulnar arteries; palmar cutaneous branches.",
        "size_anguli": 2,
        "tissue_type": "Snayu + Sandhi (joint)",
        "consequences": "Injury causes wrist drop, carpal instability, tendon adhesions, nerve palsy.",
        "protective_doctrine": "Identify median nerve before any carpal tunnel incision. Protect dorsal wrist veins — useful for IV access.",
        "shloka": {
            "sanskrit": "मणिबन्धे विद्धे हस्तकर्म नश्यति।",
            "transliteration": "Maṇibandhe viddhe hastakarma naśyati.",
            "meaning": "When Manibandha is injured, hand function is destroyed.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.30",
        },
        "procedures_at_risk": ["Carpal tunnel release", "Wrist arthroscopy", "TFCC repair", "Radial/ulnar artery repair"],
        "surgical_relevance": ["hand", "wrist", "orthopaedic", "vascular"],
    },
    {
        "id": "indravasti_arm",
        "name": "Indravasti (Arm)",
        "devanagari": "इन्द्रवस्ति (बाहु)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Sadya Pranahara",
        "risk": "Critical",
        "region": "Shakha (Upper Limb)",
        "zone": "Forearm mid-point",
        "location": "Mid-point of the forearm on the flexor aspect",
        "modern_mapping": "Anterior interosseous artery and nerve; radial artery (proximal forearm); median nerve. At risk in forearm compartment syndrome.",
        "size_anguli": 1,
        "tissue_type": "Sira (vessel)",
        "consequences": "Major vessel injury causes forearm ischaemia and gangrene. Compartment syndrome if missed.",
        "protective_doctrine": "In forearm fasciotomy, decompress all 3 compartments. Identify and protect radial artery throughout its forearm course.",
        "shloka": {
            "sanskrit": "इन्द्रवस्तौ विद्धे मृत्युः सद्यो भवति।",
            "transliteration": "Indravastau viddhe mṛtyuḥ sadyo bhavati.",
            "meaning": "Injury to Indravasti causes immediate death — reflecting the critical vascular structures here.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.14",
        },
        "procedures_at_risk": ["Forearm fasciotomy", "Radial artery harvest (RADIAL FOREARM FLAP)", "Forearm fracture ORIF"],
        "surgical_relevance": ["forearm", "vascular", "orthopaedic", "plastic"],
    },
    {
        "id": "kurpara",
        "name": "Kūrpara",
        "devanagari": "कूर्पर",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "Moderate",
        "region": "Shakha (Upper Limb)",
        "zone": "Elbow joint",
        "location": "Elbow joint (kurpara = elbow)",
        "modern_mapping": "Elbow joint; ulnar nerve at cubital tunnel; brachial artery bifurcation; medial and lateral epicondyles; common extensor/flexor origins.",
        "size_anguli": 3,
        "tissue_type": "Sandhi (joint) + Sira",
        "consequences": "Ulnar nerve injury causes claw hand (ring/little finger). Brachial artery injury causes forearm/hand ischaemia.",
        "protective_doctrine": "Always identify ulnar nerve before medial elbow dissection. In supracondylar fractures, palpate radial pulse before and after reduction.",
        "shloka": {
            "sanskrit": "कूर्परे विद्धे बाहोः कर्म नश्यति।",
            "transliteration": "Kūrpare viddhe bāhoḥ karma naśyati.",
            "meaning": "Injury to Kurpara destroys the function of the arm.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.31",
        },
        "procedures_at_risk": ["Cubital tunnel release", "Medial epicondylectomy", "Elbow arthroplasty", "Supracondylar fracture fixation"],
        "surgical_relevance": ["elbow", "orthopaedic", "vascular"],
    },
    {
        "id": "ani_arm",
        "name": "Āṇi (Arm)",
        "devanagari": "आणि (बाहु)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "Moderate",
        "region": "Shakha (Upper Limb)",
        "zone": "Distal upper arm",
        "location": "3 anguli above the elbow joint on the medial aspect of the arm",
        "modern_mapping": "Medial intermuscular septum; ulnar nerve piercing medial intermuscular septum; superior ulnar collateral artery.",
        "size_anguli": 1,
        "tissue_type": "Sira + Snayu",
        "consequences": "Injury to ulnar nerve here causes ring and little finger clawing and intrinsic muscle wasting.",
        "protective_doctrine": "During medial arm dissection for tourniquet placement, identify and protect ulnar nerve at the intermuscular septum.",
        "shloka": {
            "sanskrit": "आणौ विद्धे हस्तं वैकल्यं याति।",
            "transliteration": "Āṇau viddhe hastaṃ vaikalyaṃ yāti.",
            "meaning": "Injury to Ani causes disability of the hand.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29",
        },
        "procedures_at_risk": ["Humeral shaft fracture ORIF", "Upper arm tumour excision"],
        "surgical_relevance": ["upper_arm", "orthopaedic"],
    },
    {
        "id": "urvi_arm",
        "name": "Ūrvī (Arm)",
        "devanagari": "ऊर्वी (बाहु)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "Moderate",
        "region": "Shakha (Upper Limb)",
        "zone": "Mid upper arm",
        "location": "Mid-shaft of the humerus, anterolateral surface",
        "modern_mapping": "Radial nerve in spiral groove of humerus; profunda brachii artery; brachialis and brachioradialis muscles.",
        "size_anguli": 4,
        "tissue_type": "Mamsa + Sira",
        "consequences": "Radial nerve injury at spiral groove causes wrist drop (radial nerve palsy).",
        "protective_doctrine": "In mid-shaft humeral fractures, always assess radial nerve before and after manipulation. Posterior approach to humerus risks radial nerve in spiral groove.",
        "shloka": {
            "sanskrit": "ऊर्व्यां विद्धे भुजः शिथिलो भवति।",
            "transliteration": "Ūrvyāṃ viddhe bhujaḥ śithilo bhavati.",
            "meaning": "Injury to Urvi causes the arm to become flaccid.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.28",
        },
        "procedures_at_risk": ["Humeral shaft ORIF (posterior approach)", "Deltoid splitting"],
        "surgical_relevance": ["upper_arm", "orthopaedic"],
    },
    {
        "id": "lohitaksha_arm",
        "name": "Lohitākṣa (Arm)",
        "devanagari": "लोहिताक्ष (बाहु)",
        "count": 2,
        "sides": "bilateral",
        "classification": "Vaikalyakara",
        "risk": "High",
        "region": "Shakha (Upper Limb)",
        "zone": "Axillary fold / shoulder",
        "location": "Anterior axillary fold — junction of arm and chest wall",
        "modern_mapping": "Anterior circumflex humeral artery; axillary nerve; cephalic vein; long head of biceps tendon insertion area. Corresponds to anterolateral shoulder.",
        "size_anguli": 1,
        "tissue_type": "Sira + Mamsa",
        "consequences": "Axillary nerve injury causes deltoid palsy and shoulder abduction loss. Vascular injury causes shoulder ischaemia.",
        "protective_doctrine": "In shoulder arthroplasty and rotator cuff repair, identify axillary nerve on the undersurface of deltoid (2.5cm below acromion).",
        "shloka": {
            "sanskrit": "लोहिताक्षे विद्धे भुजः वैकल्यं याति।",
            "transliteration": "Lohitākṣe viddhe bhujaḥ vaikalyaṃ yāti.",
            "meaning": "Injury to Lohitaksha causes disability of the arm.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29",
        },
        "procedures_at_risk": ["Shoulder arthroplasty", "Rotator cuff repair", "Axillary dissection"],
        "surgical_relevance": ["shoulder", "orthopaedic", "oncology"],
    },
    {
        "id": "kakshadhara",
        "name": "Kakṣadhara",
        "devanagari": "कक्षधर",
        "count": 2,
        "sides": "bilateral",
        "classification": "Sadya Pranahara",
        "risk": "Critical",
        "region": "Shakha (Upper Limb)",
        "zone": "Axilla / shoulder joint",
        "location": "Apex of the axilla — axillary fossa proper",
        "modern_mapping": "Axillary artery and vein; brachial plexus (medial, lateral, posterior cords); axillary lymph nodes. This is the neurovascular hilum of the upper limb.",
        "size_anguli": 1,
        "tissue_type": "Sira + Snayu",
        "consequences": "Injury to axillary artery causes upper limb ischaemia. Brachial plexus injury causes complete arm paralysis (Erb-Duchenne or Klumpke palsy depending on level).",
        "protective_doctrine": "In axillary dissection (ALND), identify and protect axillary vessels and brachial plexus. Avoid blind clamping in the axilla.",
        "shloka": {
            "sanskrit": "कक्षधरे विद्धे तत्क्षणं मृत्युः।",
            "transliteration": "Kakṣadhare viddhe tatkṣaṇaṃ mṛtyuḥ.",
            "meaning": "Injury to Kakshadhara causes immediate death — reflecting the catastrophic nature of axillary vessel injury.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.14",
        },
        "procedures_at_risk": ["Axillary lymph node dissection", "Shoulder disarticulation", "Brachial plexus surgery"],
        "surgical_relevance": ["axilla", "shoulder", "oncology", "vascular"],
    },
]
