"""Lower limb Marmas — 22 points (11 per side x 2)"""
from typing import Any

LOWER_LIMB_MARMAS: list[dict[str, Any]] = [
    {
        "id": "talahridaya_foot",
        "name": "Talahṛdaya (Foot)",
        "devanagari": "तलहृदय (पाद)",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "Moderate",
        "region": "Shakha (Lower Limb)", "zone": "Plantar foot",
        "location": "Centre of the plantar surface of the foot",
        "modern_mapping": "Superficial and deep plantar arches; medial and lateral plantar nerves; intrinsic foot muscles; plantar fascia central band.",
        "size_anguli": 1, "tissue_type": "Sira + Mamsa",
        "consequences": "Injury causes plantar arch haemorrhage, intrinsic muscle damage, foot deformity (claw toes).",
        "protective_doctrine": "In plantar fascia release, avoid deep central dissection. Protect medial plantar nerve in tarsal tunnel.",
        "shloka": {
            "sanskrit": "पादतलहृदये विद्धे पादः शुष्यति।",
            "transliteration": "Pādatalahṛdaye viddhe pādaḥ śuṣyati.",
            "meaning": "Injury to Talahridaya of the foot causes the foot to wither.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.27",
        },
        "procedures_at_risk": ["Plantar fasciectomy", "Tarsal tunnel release", "Metatarsal osteotomy"],
        "surgical_relevance": ["foot", "orthopaedic"],
    },
    {
        "id": "kshipra_foot",
        "name": "Kṣipra (Foot)",
        "devanagari": "क्षिप्र (पाद)",
        "count": 2, "sides": "bilateral",
        "classification": "Sadya Pranahara", "risk": "Critical",
        "region": "Shakha (Lower Limb)", "zone": "First web space foot",
        "location": "First web space between great toe and second toe",
        "modern_mapping": "First dorsal metatarsal artery (branch of dorsalis pedis); digital nerves; first dorsal interosseous muscle.",
        "size_anguli": 1, "tissue_type": "Sira + Snayu",
        "consequences": "Injury to first dorsal metatarsal artery causes great toe ischaemia. Nerve injury causes great toe anesthesia.",
        "protective_doctrine": "Identify dorsalis pedis artery and its first branch in forefoot surgery. First web space flaps must preserve this vessel.",
        "shloka": {
            "sanskrit": "पादक्षिप्रे विद्धे मृत्युः सद्यो भवति।",
            "transliteration": "Pādakṣipre viddhe mṛtyuḥ sadyo bhavati.",
            "meaning": "Injury to Kshipra of the foot causes immediate death — reflecting the critical vascular connections here.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.15",
        },
        "procedures_at_risk": ["Hallux valgus surgery", "First web space flap", "Forefoot amputation"],
        "surgical_relevance": ["foot", "vascular", "orthopaedic"],
    },
    {
        "id": "kurcha_foot",
        "name": "Kurca (Foot)",
        "devanagari": "कूर्च (पाद)",
        "count": 2, "sides": "bilateral",
        "classification": "Rujakara", "risk": "Low",
        "region": "Shakha (Lower Limb)", "zone": "Dorsum of foot",
        "location": "Dorsum of foot at base of toes (metatarsophalangeal level)",
        "modern_mapping": "Extensor digitorum brevis; dorsalis pedis artery; dorsal venous arch; superficial peroneal nerve branches.",
        "size_anguli": 4, "tissue_type": "Mamsa",
        "consequences": "Injury causes severe foot pain, toe extension loss.",
        "protective_doctrine": "In dorsal foot incisions, identify and preserve dorsalis pedis artery. Extensor hallucis longus tendon is a landmark.",
        "shloka": {
            "sanskrit": "कूर्चे पादे विद्धे वेदना भवति।",
            "transliteration": "Kūrce pāde viddhe vedanā bhavati.",
            "meaning": "Injury to Kurca of the foot causes severe pain.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.32",
        },
        "procedures_at_risk": ["Dorsalis pedis flap", "Toe amputation", "Lisfranc ORIF"],
        "surgical_relevance": ["foot", "orthopaedic"],
    },
    {
        "id": "kurchashira_foot",
        "name": "Kūrcaśira (Foot)",
        "devanagari": "कूर्चशिर (पाद)",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "Moderate",
        "region": "Shakha (Lower Limb)", "zone": "Dorsal mid-foot",
        "location": "Mid-dorsal foot — tarsometatarsal region",
        "modern_mapping": "Lisfranc ligament complex; dorsalis pedis artery; deep peroneal nerve; extensor digitorum longus tendons.",
        "size_anguli": 2, "tissue_type": "Snayu + Asthi",
        "consequences": "Lisfranc injury causes mid-foot instability, chronic pain, flat foot deformity.",
        "protective_doctrine": "In mid-foot surgery, respect Lisfranc ligament. Dorsalis pedis pulse must be palpable after any reduction.",
        "shloka": {
            "sanskrit": "कूर्चशिरसि पादे विद्धे गतिनाशः।",
            "transliteration": "Kūrcaśirasi pāde viddhe gatināśaḥ.",
            "meaning": "Injury to Kurchashira of the foot causes loss of locomotion.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29",
        },
        "procedures_at_risk": ["Lisfranc ORIF", "Mid-foot fusion", "Tarsal coalition excision"],
        "surgical_relevance": ["foot", "orthopaedic"],
    },
    {
        "id": "gulpha",
        "name": "Gulpha",
        "devanagari": "गुल्फ",
        "count": 2, "sides": "bilateral",
        "classification": "Rujakara", "risk": "Moderate",
        "region": "Shakha (Lower Limb)", "zone": "Ankle joint",
        "location": "Ankle joint — tibiotalar articulation",
        "modern_mapping": "Ankle mortise (tibiotalar joint); medial malleolus and posterior tibial artery/nerve (medial); anterior tibial artery/deep peroneal nerve (anterior); sural nerve (lateral).",
        "size_anguli": 2, "tissue_type": "Sandhi + Snayu",
        "consequences": "Injury causes ankle instability, posterior tibial artery damage (foot ischaemia), tibial nerve damage (foot drop or sensory loss).",
        "protective_doctrine": "In ankle fracture surgery: protect sural nerve laterally, posterior tibial vessels medially. In ankle arthroplasty, identify anterior tibial artery before anterior approach.",
        "shloka": {
            "sanskrit": "गुल्फमर्मणि आघाते वेदना भवति तीव्रा।",
            "transliteration": "Gulphamarmaṇi āghāte vedanā bhavati tīvrā.",
            "meaning": "Injury to Gulpha causes intense pain.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.31",
        },
        "procedures_at_risk": ["Ankle ORIF", "Ankle arthroplasty", "Achilles tendon repair"],
        "surgical_relevance": ["ankle", "orthopaedic"],
    },
    {
        "id": "indravasti_leg",
        "name": "Indravasti (Leg)",
        "devanagari": "इन्द्रवस्ति (जङ्घा)",
        "count": 2, "sides": "bilateral",
        "classification": "Sadya Pranahara", "risk": "Critical",
        "region": "Shakha (Lower Limb)", "zone": "Mid-calf",
        "location": "Mid-point of the calf on the posterior aspect",
        "modern_mapping": "Posterior tibial artery and veins; tibial nerve; posterior tibial muscle; soleus muscle belly. Critical zone for compartment syndrome.",
        "size_anguli": 1, "tissue_type": "Sira",
        "consequences": "Posterior tibial artery injury causes foot ischaemia. Tibial nerve injury causes foot drop and plantar anaesthesia.",
        "protective_doctrine": "In 4-compartment leg fasciotomy, the posterior tibial artery runs between flexor digitorum longus and tibialis posterior — protect during medial incision.",
        "shloka": {
            "sanskrit": "इन्द्रवस्तौ जङ्घायां विद्धे मृत्युः सद्यः।",
            "transliteration": "Indravastau jaṅghāyāṃ viddhe mṛtyuḥ sadyaḥ.",
            "meaning": "Injury to Indravasti of the leg causes immediate death.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.14",
        },
        "procedures_at_risk": ["Leg fasciotomy", "Posterior tibial artery repair", "Tibial fracture nailing"],
        "surgical_relevance": ["leg", "vascular", "orthopaedic"],
    },
    {
        "id": "janu",
        "name": "Jānu",
        "devanagari": "जानु",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "High",
        "region": "Shakha (Lower Limb)", "zone": "Knee joint",
        "location": "Knee joint — tibiofemoral and patellofemoral articulations",
        "modern_mapping": "Popliteal artery and vein; tibial and common peroneal nerve; ACL, PCL, medial and lateral menisci; popliteal lymph nodes.",
        "size_anguli": 3, "tissue_type": "Sandhi + Sira + Snayu",
        "consequences": "Popliteal artery injury causes catastrophic limb ischaemia (golden hour < 6 hours). Peroneal nerve injury causes foot drop.",
        "protective_doctrine": "In total knee arthroplasty: use tourniquet, identify popliteal vessels before posterior capsule release. In ACL surgery, protect peroneal nerve during lateral portal placement.",
        "shloka": {
            "sanskrit": "जानुमर्मणि विद्धे जानु स्तब्धं भवति।",
            "transliteration": "Jānumarmaṇi viddhe jānu stabdhaṃ bhavati.",
            "meaning": "Injury to Janu Marma causes stiffness and immobility of the knee.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.30",
        },
        "procedures_at_risk": ["Total knee arthroplasty", "ACL reconstruction", "Popliteal artery repair", "Knee arthroscopy"],
        "surgical_relevance": ["knee", "orthopaedic", "vascular"],
    },
    {
        "id": "ani_leg",
        "name": "Āṇi (Leg)",
        "devanagari": "आणि (ऊरु)",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "Moderate",
        "region": "Shakha (Lower Limb)", "zone": "Distal thigh",
        "location": "3 anguli above the knee on the medial aspect",
        "modern_mapping": "Saphenous nerve and artery; adductor canal contents (superficial femoral artery, femoral vein); vastus medialis muscle.",
        "size_anguli": 1, "tissue_type": "Sira + Snayu",
        "consequences": "Injury to superficial femoral artery causes below-knee ischaemia. Saphenous nerve damage causes medial knee and leg hypoesthesia.",
        "protective_doctrine": "In adductor canal block and femoral-popliteal bypass, identify and protect saphenous nerve running with the long saphenous vein.",
        "shloka": {
            "sanskrit": "आणौ ऊरौ विद्धे पादो वैकल्यं याति।",
            "transliteration": "Āṇau ūrau viddhe pādo vaikalyaṃ yāti.",
            "meaning": "Injury to Ani of the thigh causes disability of the leg.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29",
        },
        "procedures_at_risk": ["Femoral artery bypass", "Adductor canal block", "Distal femur ORIF"],
        "surgical_relevance": ["thigh", "vascular", "orthopaedic"],
    },
    {
        "id": "urvi_thigh",
        "name": "Ūrvī (Thigh)",
        "devanagari": "ऊर्वी (ऊरु)",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "Moderate",
        "region": "Shakha (Lower Limb)", "zone": "Mid-thigh",
        "location": "Mid-shaft of femur, anteromedial surface",
        "modern_mapping": "Superficial femoral artery in adductor canal; femoral nerve branches to quadriceps; deep femoral artery (profunda femoris); vastus intermedius.",
        "size_anguli": 4, "tissue_type": "Mamsa + Sira",
        "consequences": "Major vessel injury causes massive haemorrhage. Femoral nerve injury causes quadriceps palsy and inability to extend knee.",
        "protective_doctrine": "In femoral shaft fracture nailing, use traction table and identify correct entry point. In anterior approach, protect femoral nerve lateral to femoral artery.",
        "shloka": {
            "sanskrit": "ऊर्व्यां विद्धे पादः शिथिलो भवति।",
            "transliteration": "Ūrvyāṃ viddhe pādaḥ śithilo bhavati.",
            "meaning": "Injury to Urvi of the thigh causes the leg to become flaccid.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.28",
        },
        "procedures_at_risk": ["Femoral shaft nailing", "Thigh tumour excision", "Femoral artery repair"],
        "surgical_relevance": ["thigh", "orthopaedic", "vascular"],
    },
    {
        "id": "lohitaksha_thigh",
        "name": "Lohitākṣa (Thigh)",
        "devanagari": "लोहिताक्ष (ऊरु)",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "High",
        "region": "Shakha (Lower Limb)", "zone": "Groin / femoral triangle",
        "location": "Femoral triangle — upper anterior thigh",
        "modern_mapping": "Femoral artery, vein, nerve in femoral triangle (NAVY: Nerve-Artery-Vein-Y-fronts from lateral to medial). Deep inguinal lymph nodes.",
        "size_anguli": 1, "tissue_type": "Sira + Mamsa",
        "consequences": "Femoral artery injury causes lower limb ischaemia. Femoral nerve injury causes quadriceps paralysis.",
        "protective_doctrine": "In inguinal hernia repair, identify femoral vessels and nerve in femoral triangle. In TAPP/TEP, avoid tacking below iliopubic tract (triangle of doom).",
        "shloka": {
            "sanskrit": "लोहिताक्षे ऊरौ विद्धे पादो वैकल्यं याति।",
            "transliteration": "Lohitākṣe ūrau viddhe pādo vaikalyaṃ yāti.",
            "meaning": "Injury to Lohitaksha of the thigh causes disability of the leg.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29",
        },
        "procedures_at_risk": ["Femoral hernia repair", "TAPP/TEP hernioplasty", "Femoral artery cannulation", "Total hip arthroplasty"],
        "surgical_relevance": ["groin", "vascular", "hernia", "orthopaedic"],
    },
    {
        "id": "vitapa",
        "name": "Vitapa",
        "devanagari": "विटप",
        "count": 2, "sides": "bilateral",
        "classification": "Vaikalyakara", "risk": "High",
        "region": "Shakha (Lower Limb)", "zone": "Inguinal/scrotal junction",
        "location": "Groin crease at junction of thigh and scrotum/labia",
        "modern_mapping": "Spermatic cord (male) / round ligament (female); ilioinguinal and genitofemoral nerves; inguinal canal contents. In classical anatomy corresponds to the inguinal Marma.",
        "size_anguli": 1, "tissue_type": "Sira + Snayu",
        "consequences": "Injury causes genital numbness (ilioinguinal nerve), vas deferens damage (infertility in males), cremasteric muscle damage.",
        "protective_doctrine": "In inguinal hernia repair, identify and protect ilioinguinal nerve, iliohypogastric nerve, and vas deferens. Avoid excessive traction on spermatic cord.",
        "shloka": {
            "sanskrit": "विटपे विद्धे पुंस्त्वनाशः।",
            "transliteration": "Vitape viddhe puṃstvanāśaḥ.",
            "meaning": "Injury to Vitapa causes loss of male virility — reflecting damage to spermatic cord structures.",
            "reference": "Suśruta Saṃhitā, Śārīrasthāna 6.29; Aṣṭāṅgahṛdayam, Śārīrasthāna 4.12",
        },
        "procedures_at_risk": ["Inguinal hernia repair (open/laparoscopic)", "Orchidopexy", "Hydrocelectomy"],
        "surgical_relevance": ["groin", "urology", "hernia"],
    },
]
