"""
ShalyaMitra — Live NIM Session Handler

REAL NVIDIA Nemotron 49B inference during simulated surgery.
Vitals are simulated (no monitors), but every Nael response
is generated by a real NIM API call through the Privacy Router.
"""

from __future__ import annotations
import asyncio, json, math, time
from typing import Optional
from fastapi import WebSocket, WebSocketDisconnect
import orjson

from app.config import settings
from app.models.schemas import AriaMode


def vitals_at(t: float) -> dict:
    hr = round(72 + 6 * math.sin(t / 12) + (22 if 200 < t < 225 else 0))
    spo2 = max(88, round(98 - (6 if 205 < t < 220 else 0) + math.sin(t / 9)))
    map_val = round(82 + 4 * math.sin(t / 18) - (14 if 200 < t < 225 else 0))
    etco2 = round(35 + 2 * math.sin(t / 7) + (4 if 205 < t < 220 else 0))
    temp = round(36.4 + 0.1 * math.sin(t / 60), 1)
    rr = round(14 + 2 * math.sin(t / 15))
    return {"hr": hr, "spo2": spo2, "map": map_val, "etco2": etco2, "temp": temp, "rr": rr}


# Surgical scenario timeline — surgeon lines + NIM prompt triggers
NIM_SCENARIO = [
    {"at": 0,  "type": "phase", "phase": "preparation"},
    {"at": 2,  "type": "system", "text": "All systems connected. NIM API active. Nael is listening."},
    {"at": 6,  "type": "nim", "ctx": "Session started for laparoscopic cholecystectomy. Patient: 52yr male, BMI 31, ASA-II, gallstone pancreatitis history. Greet the surgeon and summarize 2 key risk factors."},
    {"at": 14, "type": "surgeon", "text": "Patient asleep, paralysed, ready for prep."},
    {"at": 18, "type": "surgeon", "text": "Confirming patient identity. Time-out please."},
    {"at": 24, "type": "surgeon", "text": "Time-out complete. Antibiotic given at induction."},
    {"at": 26, "type": "nim", "ctx": "Time-out completed and antibiotic prophylaxis given at induction. Acknowledge and confirm logged per WHO Surgical Safety Checklist."},
    {"at": 30, "type": "phase", "phase": "access"},
    {"at": 32, "type": "surgeon", "text": "Veress needle in. Starting insufflation to 12 mmHg."},
    {"at": 36, "type": "nim", "ctx": "Surgeon started pneumoperitoneum with Veress needle at 12mmHg. Provide brief safety note about intra-abdominal pressure limits."},
    {"at": 45, "type": "alert", "ctx": "Instrument count started: 14 instruments, 6 swabs deployed. Generate brief tracking alert as Sentinel agent.", "sev": "info"},
    {"at": 60, "type": "phase", "phase": "dissection"},
    {"at": 62, "type": "surgeon", "text": "Three working ports in. Camera in. Retracting fundus."},
    {"at": 67, "type": "nim", "ctx": "Dissection phase begun. Surgeon retracting gallbladder fundus. Mention Critical View of Safety requirement before clipping."},
    {"at": 85, "type": "alert", "ctx": "Critical View of Safety NOT yet achieved during Calot's triangle dissection. Alert: what CVS requires (2 structures, hepatocystic triangle cleared).", "sev": "caution"},
    {"at": 96, "type": "nim", "ctx": "HR risen from 78 to 96 bpm during dissection. MAP 74. Likely surgical stress response. Brief monitoring note as Monitor Sentinel.", "role": "monitor"},
    {"at": 122, "type": "nim", "ctx": "Dissecting near hepatoduodenal ligament. As Oracle agent, brief advisory about Nabhi Marma from Sushruta Samhita and its modern correlation to portal triad."},
    {"at": 150, "type": "alert", "ctx": "Fentanyl 100mcg IV administered. As Pharmacist agent, log drug, confirm no interactions, state expected peak effect time.", "sev": "info"},
    {"at": 172, "type": "surgeon", "text": "I have the cystic duct and artery clearly."},
    {"at": 175, "type": "nim", "ctx": "Surgeon confirms cystic duct and artery clearly identified. Evaluate if Critical View of Safety criteria are met."},
    {"at": 210, "type": "haem", "ctx": "Pulsatile bleeding detected lateral to dissection in Calot's triangle. Confidence 94%. Generate EMERGENCY alert with immediate actions."},
    {"at": 222, "type": "surgeon", "text": "That's controlled. Small cystic artery branch — cauterised."},
    {"at": 226, "type": "nim", "ctx": "Bleeding controlled — small cystic artery branch cauterised. Confirm haemorrhage resolved, return to normal monitoring."},
    {"at": 245, "type": "nim", "ctx": "Cystic artery and duct clipped and divided. No bleeding. Confirm successful division, note clip counts for operative record."},
    {"at": 300, "type": "phase", "phase": "closure"},
    {"at": 302, "type": "surgeon", "text": "Gallbladder fully detached. Specimen out."},
    {"at": 310, "type": "nim", "ctx": "Gallbladder retrieved. As Sentinel, confirm instrument count: 14/14 instruments, 6/6 swabs accounted."},
    {"at": 325, "type": "surgeon", "text": "Closing fascia. Skin closure with subcuticular."},
    {"at": 342, "type": "nim", "ctx": "Surgery complete. As Chronicler, provide 3-line operative summary: procedure, key findings (controlled bleed, CVS achieved), outcome."},
    {"at": 355, "type": "system", "text": "Session complete. All Nael responses used real NVIDIA Nemotron 49B via NIM API."},
]

SYSTEM_PROMPTS = {
    "surgical_ai": (
        "You are Nael, the AI surgical intelligence assistant in ShalyaMitra. "
        "You are in a live operating theatre during surgery. Keep responses concise (2-3 sentences max), "
        "clinically precise, and speak in present tense. Never add disclaimers. Respond as a confident surgical co-pilot."
    ),
    "monitor": (
        "You are the Monitor Sentinel agent. You analyse vital signs during surgery. "
        "Keep responses to 1-2 sentences. Be factual and clinical."
    ),
    "haemorrhage": (
        "You are the Haemorrhage Sentinel — emergency bleeding detection agent. "
        "Generate urgent, action-oriented alerts. 2-3 sentences maximum."
    ),
}


async def _nim_infer(prompt: str, role: str = "surgical_ai") -> str:
    """Make a real NIM API call through the Privacy Router."""
    from app.safety.privacy_router import get_privacy_router

    messages = [
        {"role": "system", "content": SYSTEM_PROMPTS.get(role, SYSTEM_PROMPTS["surgical_ai"])},
        {"role": "user", "content": prompt},
    ]

    router = get_privacy_router()
    result = await router.infer(messages, agent_type="VoiceAgent", max_tokens=200, temperature=0.4)

    if "error" in result:
        return f"[NIM unavailable: {result['error'][:80]}]"

    try:
        return result["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError):
        return "[NIM response parsing error]"


async def handle_nim_session(ws: WebSocket, mode: AriaMode):
    """
    LIVE NIM SESSION — Real NVIDIA Nemotron 49B inference.
    Every Nael response is a real NIM API call through Privacy Router.
    """
    start = time.monotonic()
    cursor = 0

    await ws.send_text(orjson.dumps({
        "type": "transcript", "speaker": "system",
        "text": "\U0001f534 LIVE NIM MODE — Real NVIDIA Nemotron 49B inference active.",
        "at": 0, "pillar": "nael",
    }).decode())

    try:
        while True:
            el = time.monotonic() - start
            if el >= 370:
                await ws.send_text(orjson.dumps({
                    "type": "transcript", "speaker": "system",
                    "text": "Live NIM session complete.", "at": el,
                }).decode())
                break

            # Vitals every second
            await ws.send_text(orjson.dumps({"type": "vitals", "at": el, **vitals_at(el)}).decode())

            # Fire due events
            while cursor < len(NIM_SCENARIO) and NIM_SCENARIO[cursor]["at"] <= el:
                e = NIM_SCENARIO[cursor]
                cursor += 1
                t = e["type"]

                if t == "phase":
                    await ws.send_text(orjson.dumps({"type": "phase", "phase": e["phase"], "confidence": 1.0, "at": el}).decode())

                elif t == "system":
                    await ws.send_text(orjson.dumps({"type": "transcript", "speaker": "system", "text": e["text"], "at": el, "pillar": "nael"}).decode())

                elif t == "surgeon":
                    await ws.send_text(orjson.dumps({"type": "transcript", "speaker": "surgeon", "text": e["text"], "at": el}).decode())

                elif t == "nim":
                    resp = await _nim_infer(e["ctx"], e.get("role", "surgical_ai"))
                    await ws.send_text(orjson.dumps({"type": "transcript", "speaker": "nael", "text": resp, "at": el, "pillar": "nael"}).decode())

                elif t == "alert":
                    txt = await _nim_infer(e["ctx"])
                    sev = e.get("sev", "info")
                    if mode == AriaMode.silent and sev != "critical":
                        continue
                    await ws.send_text(orjson.dumps({
                        "type": "alert", "severity": sev,
                        "title": txt[:60], "body": txt,
                        "source": "nim-live", "at": el,
                        "pillar": "nael", "priority": 3 if sev == "info" else 2,
                    }).decode())

                elif t == "haem":
                    txt = await _nim_infer(e["ctx"], "haemorrhage")
                    await ws.send_text(orjson.dumps({
                        "type": "alert", "severity": "critical",
                        "title": "\u26a0 POSSIBLE ARTERIAL BLEED",
                        "body": txt, "source": "haemorrhage-sentinel",
                        "at": el, "pillar": "haemorrhage", "priority": 1,
                    }).decode())
                    await ws.send_text(orjson.dumps({"type": "transcript", "speaker": "nael", "text": txt, "at": el, "pillar": "haemorrhage"}).decode())

            # Client messages
            try:
                raw = await asyncio.wait_for(ws.receive_text(), timeout=0.05)
                msg = json.loads(raw)
                if msg.get("type") == "control":
                    mode = AriaMode(msg.get("mode", "reactive"))
                elif msg.get("type") == "ping":
                    await ws.send_text(orjson.dumps({"type": "pong", "ts": msg.get("ts", 0)}).decode())
            except asyncio.TimeoutError:
                pass

            await asyncio.sleep(1.0)

    except WebSocketDisconnect:
        pass
    except Exception as ex:
        print(f"[NIM SESSION ERROR] {ex}")
        try:
            await ws.send_text(orjson.dumps({"type": "error", "code": "nim_error", "message": str(ex)[:100]}).decode())
        except Exception:
            pass
