/**
 * ShalyaMitra Procedure Catalogue
 * Two domains: Ayurveda (Shalya Tantra) and Modern (Allopathy)
 */

export type ProcedureEntry = {
  id: string;
  label: string;       // display name (may include Sanskrit)
  category?: string;
  custom?: boolean;    // "type below" entry
};

// ── AYURVEDA / SHALYA TANTRA ─────────────────────────────────────────────

export const AYURVEDA_PROCEDURES: ProcedureEntry[] = [
  { id: "ay_01", label: "Ksharasutra (क्षारसूत्र) — Medicated Thread" },
  { id: "ay_02", label: "Agnikarma (अग्निकर्म) — Thermal Cautery" },
  { id: "ay_03", label: "Jalaukavacharana (जलौकावचारण) — Leech Therapy" },
  { id: "ay_04", label: "Siravyadha (सिराव्यध) — Venesection" },
  { id: "ay_05", label: "Bhagandara (भगन्दर) — Fistula-in-Ano" },
  { id: "ay_06", label: "Arshas (अर्श) — Haemorrhoids" },
  { id: "ay_07", label: "Ashmari Chedana (अश्मरी) — Urolithiasis" },
  { id: "ay_08", label: "Granthi Chedana (ग्रन्थि) — Cyst Excision" },
  { id: "ay_09", label: "Nadi Vrana (नाडी व्रण) — Sinus / Fistula" },
  { id: "ay_10", label: "Arbuda Chikitsa (अर्बुद) — Tumour" },
  { id: "ay_11", label: "Vrana Chikitsa (व्रण) — General Wound Care" },
  { id: "ay_12", label: "Debridement, Fasciotomy, Curettage" },
  { id: "ay_13", label: "Drainage of Abscess — Perianal / Breast / Axillary / Cellulitis" },
  { id: "ay_14", label: "Skin Grafting (All Types) & Ear Lobe Repair" },
  { id: "ay_15", label: "Excision of Simple Cysts & Benign Tumours" },
  { id: "ay_16", label: "Excision / Amputation in Gangrene" },
  { id: "ay_17", label: "Traumatic Wound Management — Suturing, Ligatures" },
  { id: "ay_18", label: "Removal of Foreign Bodies from Non-vital Organs" },
  { id: "ay_19", label: "Closed Reduction, Immobilisation, Splints & Cast" },
  { id: "ay_20", label: "Reduction of Dislocation and Subluxation" },
  { id: "ay_21", label: "Laparotomy" },
  { id: "ay_22", label: "Hemorrhoidectomy — Open/Closed, RBL, Sclerotherapy" },
  { id: "ay_23", label: "Fissure-in-Ano — Anal Dilatation, Sphincterotomy" },
  { id: "ay_24", label: "Fistulectomy and Fistulotomy" },
  { id: "ay_25", label: "Excision of Pilonidal Sinus" },
  { id: "ay_26", label: "Rectopexy (Various Types)" },
  { id: "ay_27", label: "Suprapubic Cystostomy and Cystolithotomy" },
  { id: "ay_28", label: "Urethral Dilatation and Meatotomy" },
  { id: "ay_29", label: "Circumcision" },
  { id: "ay_30", label: "Hernia Surgery — Inguinal / Umbilical / Femoral / Incisional" },
  { id: "ay_31", label: "Hydrocele — Eversion of Sac" },
  { id: "ay_32", label: "Intercostal Drain Insertion for Thoracic Trauma" },
  { id: "ay_33", label: "Ligation — Haemangioma, Varicose Veins, Varicocele" },
  { id: "ay_34", label: "Excision of Benign Breast Lesions & Lump Biopsy" },
  { id: "ay_35", label: "Exploratory Laparotomy" },
  { id: "ay_36", label: "Foreign Body Removal from Stomach" },
  { id: "ay_37", label: "Video Proctoscopy and Sigmoidoscopy" },
  { id: "ay_38", label: "Ileostomy, Colostomy, Emergency Resection and Anastomosis" },
  { id: "ay_39", label: "Sigmoidoscopic Biopsy and Polypectomy" },
  { id: "ay_40", label: "Appendicectomy" },
  { id: "ay_41", label: "Cholecystectomy" },
  { id: "ay_42", label: "Airway Management — LMA, Endotracheal Intubation" },
  { id: "ay_43", label: "Excision of Calcified Plaque in Peyronie's Disease" },
  { id: "ay_44", label: "Orchidopexy and Orchidectomy" },
  { id: "ay_45", label: "Eyelid Surgery — Sling, Correction, I&D, Curettage" },
  { id: "ay_46", label: "Pterygium Excision — CLAU / Amniotic Membrane Graft" },
  { id: "ay_47", label: "Iris Prolapse Excision Surgery" },
  { id: "ay_48", label: "Glaucoma — Trabeculectomy" },
  { id: "ay_49", label: "Ocular Trauma Repair — Lid, Conjunctiva, Sclera, Cornea" },
  { id: "ay_50", label: "Squint Surgery — Esotropia / Exotropia" },
  { id: "ay_51", label: "Dacryocystitis — DCT and Dacryocystorhinostomy (DCR)" },
  { id: "ay_52", label: "Cataract Surgery — Phacoemulsification with IOL Implantation" },
  { id: "ay_53", label: "Local Anaesthesia Techniques in Eye Surgery" },
  { id: "ay_54", label: "Deviated Nasal Septum — Septoplasty" },
  { id: "ay_55", label: "Nasal Polyp — Polypectomy" },
  { id: "ay_56", label: "Deformed Nose — Rhinoplasty" },
  { id: "ay_57", label: "Torn Ear Lobule — Lobuloplasty" },
  { id: "ay_58", label: "ASOM / Glue Ear — Myringotomy" },
  { id: "ay_59", label: "CSOM — Tympanoplasty & Mastoidectomy" },
  { id: "ay_60", label: "Peritonsillar Abscess (Quinsy) — I&D" },
  { id: "ay_61", label: "Chronic Tonsillitis — Tonsillectomy" },
  { id: "ay_62", label: "Cleft Lip (Hare Lip) Repair" },
  { id: "ay_63", label: "Tooth Extraction — Loose / Impacted" },
  { id: "ay_64", label: "Dental Caries — Root Canal Treatment" },
  { id: "ay_65", label: "Thyroidectomy" },
  { id: "ay_66", label: "Mastectomy" },
  { id: "ay_67", label: "Colectomy" },
  { id: "ay_68", label: "Whipple Procedure (Pancreaticoduodenectomy)" },
  { id: "ay_69", label: "Nephrectomy" },
  { id: "ay_70", label: "TURP (Transurethral Resection of Prostate)" },
  { id: "ay_71", label: "Radical Prostatectomy" },
  { id: "ay_72", label: "Caesarean Section" },
  { id: "ay_73", label: "Hysterectomy" },
  { id: "ay_74", label: "Tracheostomy" },
  { id: "ay_75", label: "Trauma Laparotomy" },
  { id: "ay_76", label: "Total Knee Replacement" },
  { id: "ay_77", label: "Total Hip Replacement" },
  { id: "ay_78", label: "ACL Reconstruction" },
  { id: "ay_79", label: "Spinal Fusion" },
  { id: "ay_80", label: "Laminectomy / Discectomy" },
  { id: "ay_83", label: "Craniotomy" },
  { id: "ay_84", label: "Student Training Session" },
  { id: "ay_85", label: "Anatomy Demonstration" },
  { id: "ay_86", label: "Documentation & Recording Session" },
  { id: "ay_87", label: "Custom / Other Procedure", custom: true },
];

// ── MODERN / ALLOPATHY ───────────────────────────────────────────────────

export const MODERN_PROCEDURES: ProcedureEntry[] = [
  // General Surgery
  { id: "mo_01", label: "Appendicectomy (Open / Laparoscopic)", category: "General Surgery" },
  { id: "mo_02", label: "Cholecystectomy — Laparoscopic / Open", category: "General Surgery" },
  { id: "mo_03", label: "Hernia Repair — Inguinal (Lichtenstein / TEP / TAPP)", category: "General Surgery" },
  { id: "mo_04", label: "Hernia Repair — Umbilical / Epigastric", category: "General Surgery" },
  { id: "mo_05", label: "Hernia Repair — Incisional / Ventral (Mesh)", category: "General Surgery" },
  { id: "mo_06", label: "Hernia Repair — Femoral", category: "General Surgery" },
  { id: "mo_07", label: "Thyroidectomy — Total / Hemithyroidectomy", category: "General Surgery" },
  { id: "mo_08", label: "Parathyroidectomy", category: "General Surgery" },
  { id: "mo_09", label: "Parotidectomy — Superficial / Total", category: "General Surgery" },
  { id: "mo_10", label: "Mastectomy — Total / Radical / Modified Radical", category: "General Surgery" },
  { id: "mo_11", label: "Breast Lump Excision / Wide Local Excision", category: "General Surgery" },
  { id: "mo_12", label: "Sentinel Node Biopsy", category: "General Surgery" },
  { id: "mo_13", label: "Colectomy — Right / Left / Total", category: "General Surgery" },
  { id: "mo_14", label: "Whipple Procedure (Pancreaticoduodenectomy)", category: "General Surgery" },
  { id: "mo_15", label: "Gastrectomy — Partial / Total", category: "General Surgery" },
  { id: "mo_16", label: "Splenectomy — Elective / Emergency", category: "General Surgery" },
  { id: "mo_17", label: "Liver Resection — Hepatectomy", category: "General Surgery" },
  { id: "mo_18", label: "Bariatric Surgery — Sleeve Gastrectomy", category: "General Surgery" },
  { id: "mo_19", label: "Bariatric Surgery — Roux-en-Y Gastric Bypass", category: "General Surgery" },
  { id: "mo_20", label: "Colorectal — Anterior Resection / APR / Hartmann's", category: "General Surgery" },
  { id: "mo_21", label: "Hemorrhoidectomy — Milligan-Morgan / Ferguson / Stapled", category: "General Surgery" },
  { id: "mo_22", label: "Fistulectomy / Fistulotomy — Fistula-in-Ano", category: "General Surgery" },
  { id: "mo_23", label: "Pilonidal Sinus Excision", category: "General Surgery" },
  { id: "mo_24", label: "Abscess Drainage — Perianal / Breast / Deep", category: "General Surgery" },
  { id: "mo_25", label: "Diagnostic Laparoscopy", category: "General Surgery" },
  { id: "mo_26", label: "Exploratory Laparotomy", category: "General Surgery" },
  { id: "mo_27", label: "Surgical Debridement & Wound Management", category: "General Surgery" },
  { id: "mo_28", label: "Stoma Formation — Colostomy / Ileostomy", category: "General Surgery" },
  { id: "mo_29", label: "Tracheostomy — Elective / Emergency", category: "General Surgery" },
  // Orthopaedic
  { id: "mo_30", label: "Total Knee Replacement (TKR)", category: "Orthopaedic Surgery" },
  { id: "mo_31", label: "Total Hip Replacement (THR)", category: "Orthopaedic Surgery" },
  { id: "mo_32", label: "ACL Reconstruction — Hamstring / Patellar Graft", category: "Orthopaedic Surgery" },
  { id: "mo_33", label: "PCL Reconstruction", category: "Orthopaedic Surgery" },
  { id: "mo_34", label: "Shoulder Arthroscopy — Bankart / SLAP / Subacromial", category: "Orthopaedic Surgery" },
  { id: "mo_35", label: "Rotator Cuff Repair", category: "Orthopaedic Surgery" },
  { id: "mo_36", label: "Knee Arthroscopy — Meniscectomy / Chondroplasty", category: "Orthopaedic Surgery" },
  { id: "mo_37", label: "Spinal Fusion — Cervical / Lumbar (ACDF / PLIF / TLIF)", category: "Orthopaedic Surgery" },
  { id: "mo_38", label: "Laminectomy / Discectomy", category: "Orthopaedic Surgery" },
  { id: "mo_39", label: "ORIF — Femur (Intertrochanteric / Shaft / Neck)", category: "Orthopaedic Surgery" },
  { id: "mo_40", label: "ORIF — Tibia / Fibula", category: "Orthopaedic Surgery" },
  { id: "mo_41", label: "ORIF — Radius / Ulna / Distal Radius", category: "Orthopaedic Surgery" },
  { id: "mo_42", label: "ORIF — Humerus / Clavicle", category: "Orthopaedic Surgery" },
  { id: "mo_43", label: "ORIF — Pelvis / Acetabulum", category: "Orthopaedic Surgery" },
  { id: "mo_44", label: "Intramedullary Nailing — Femur", category: "Orthopaedic Surgery" },
  { id: "mo_45", label: "Intramedullary Nailing — Tibia", category: "Orthopaedic Surgery" },
  { id: "mo_46", label: "Amputation — BK / AK / Digital", category: "Orthopaedic Surgery" },
  { id: "mo_47", label: "Carpal Tunnel Release", category: "Orthopaedic Surgery" },
  { id: "mo_48", label: "Dupuytren's Contracture Release", category: "Orthopaedic Surgery" },
  // Cardiothoracic
  { id: "mo_49", label: "CABG — Coronary Artery Bypass Grafting", category: "Cardiothoracic Surgery" },
  { id: "mo_50", label: "Aortic Valve Replacement (AVR)", category: "Cardiothoracic Surgery" },
  { id: "mo_51", label: "Mitral Valve Replacement / Repair (MVR)", category: "Cardiothoracic Surgery" },
  { id: "mo_52", label: "VATS — Video-Assisted Thoracoscopic Surgery", category: "Cardiothoracic Surgery" },
  { id: "mo_53", label: "Lobectomy — Lung", category: "Cardiothoracic Surgery" },
  { id: "mo_54", label: "Pneumonectomy", category: "Cardiothoracic Surgery" },
  { id: "mo_55", label: "Thoracotomy — Exploratory / Decortication", category: "Cardiothoracic Surgery" },
  { id: "mo_56", label: "Pericardial Window", category: "Cardiothoracic Surgery" },
  { id: "mo_57", label: "ASD / VSD Closure", category: "Cardiothoracic Surgery" },
  { id: "mo_58", label: "Aortic Aneurysm Repair (Open / EVAR)", category: "Cardiothoracic Surgery" },
  { id: "mo_59", label: "Intercostal Drain / Chest Tube Insertion", category: "Cardiothoracic Surgery" },
  // Neurosurgery
  { id: "mo_60", label: "Craniotomy — Tumour / Abscess / Haematoma", category: "Neurosurgery" },
  { id: "mo_61", label: "VP Shunt / Ventriculoperitoneal Shunt", category: "Neurosurgery" },
  { id: "mo_62", label: "Decompressive Craniectomy", category: "Neurosurgery" },
  { id: "mo_63", label: "Burr Hole — EDH / SDH / Biopsy", category: "Neurosurgery" },
  { id: "mo_64", label: "Intracranial Aneurysm Clipping", category: "Neurosurgery" },
  { id: "mo_65", label: "Deep Brain Stimulation (DBS)", category: "Neurosurgery" },
  { id: "mo_66", label: "Transsphenoidal Pituitary Surgery", category: "Neurosurgery" },
  { id: "mo_67", label: "Spinal Stabilisation — Posterior Instrumentation", category: "Neurosurgery" },
  { id: "mo_68", label: "Cervical Disc Replacement / ACDF", category: "Neurosurgery" },
  // Urology
  { id: "mo_69", label: "Nephrectomy — Simple / Radical / Partial", category: "Urology" },
  { id: "mo_70", label: "TURP (Transurethral Resection of Prostate)", category: "Urology" },
  { id: "mo_71", label: "Radical Prostatectomy — Open / Robotic", category: "Urology" },
  { id: "mo_72", label: "Cystectomy — Partial / Radical", category: "Urology" },
  { id: "mo_73", label: "Pyeloplasty — Anderson-Hynes", category: "Urology" },
  { id: "mo_74", label: "Ureteric Reimplantation — Cohen / Politano", category: "Urology" },
  { id: "mo_75", label: "PCNL — Percutaneous Nephrolithotomy", category: "Urology" },
  { id: "mo_76", label: "URSL — Ureteroscopic Stone Removal", category: "Urology" },
  { id: "mo_77", label: "Orchiectomy — Simple / Radical", category: "Urology" },
  { id: "mo_78", label: "Orchidopexy — Undescended Testis", category: "Urology" },
  { id: "mo_79", label: "Hydrocele Repair", category: "Urology" },
  { id: "mo_80", label: "Circumcision", category: "Urology" },
  { id: "mo_81", label: "AV Fistula Formation for Dialysis", category: "Urology" },
  { id: "mo_82", label: "Cystoscopy — Diagnostic / TURBT", category: "Urology" },
  // Vascular
  { id: "mo_83", label: "Fem-Pop Bypass Grafting", category: "Vascular Surgery" },
  { id: "mo_84", label: "Carotid Endarterectomy (CEA)", category: "Vascular Surgery" },
  { id: "mo_85", label: "Varicose Vein Surgery — Stripping / EVLA / FOAM", category: "Vascular Surgery" },
  { id: "mo_86", label: "Embolectomy — Femoral / Iliac", category: "Vascular Surgery" },
  { id: "mo_87", label: "AAA Repair — Open / Elective", category: "Vascular Surgery" },
  // Plastic & Reconstructive
  { id: "mo_88", label: "Skin Grafting — Split / Full Thickness", category: "Plastic & Reconstructive" },
  { id: "mo_89", label: "Flap Surgery — Local / Pedicled / Free", category: "Plastic & Reconstructive" },
  { id: "mo_90", label: "Burns Management — Escharotomy / Grafting", category: "Plastic & Reconstructive" },
  { id: "mo_91", label: "Cleft Lip Repair — Millard / Tennison", category: "Plastic & Reconstructive" },
  { id: "mo_92", label: "Cleft Palate Repair", category: "Plastic & Reconstructive" },
  { id: "mo_93", label: "Breast Reconstruction — Implant / TRAM / DIEP", category: "Plastic & Reconstructive" },
  { id: "mo_94", label: "Hand Surgery — Tendon Repair / Nerve Repair", category: "Plastic & Reconstructive" },
  { id: "mo_95", label: "Scar Revision / Keloid Excision", category: "Plastic & Reconstructive" },
  // OBG
  { id: "mo_96",  label: "Caesarean Section — LSCS", category: "Obstetrics & Gynaecology" },
  { id: "mo_97",  label: "Hysterectomy — TAH / LAVH / Radical", category: "Obstetrics & Gynaecology" },
  { id: "mo_98",  label: "Ovarian Cystectomy — Laparoscopic", category: "Obstetrics & Gynaecology" },
  { id: "mo_99",  label: "Myomectomy — Open / Laparoscopic", category: "Obstetrics & Gynaecology" },
  { id: "mo_100", label: "Tubal Ligation", category: "Obstetrics & Gynaecology" },
  { id: "mo_101", label: "Diagnostic Laparoscopy — Gynaecological", category: "Obstetrics & Gynaecology" },
  { id: "mo_102", label: "Ectopic Pregnancy — Salpingectomy / Salpingostomy", category: "Obstetrics & Gynaecology" },
  { id: "mo_103", label: "D&C — Dilatation & Curettage", category: "Obstetrics & Gynaecology" },
  // ENT
  { id: "mo_104", label: "Tonsillectomy — Cold Steel / Coblation", category: "ENT Surgery" },
  { id: "mo_105", label: "Septoplasty — Deviated Nasal Septum", category: "ENT Surgery" },
  { id: "mo_106", label: "FESS — Functional Endoscopic Sinus Surgery", category: "ENT Surgery" },
  { id: "mo_107", label: "Mastoidectomy — Cortical / Modified Radical", category: "ENT Surgery" },
  { id: "mo_108", label: "Tympanoplasty — Type I / II / III", category: "ENT Surgery" },
  { id: "mo_109", label: "Cochlear Implant Surgery", category: "ENT Surgery" },
  { id: "mo_110", label: "Laryngectomy — Total / Partial", category: "ENT Surgery" },
  { id: "mo_111", label: "Rhinoplasty — Functional / Cosmetic", category: "ENT Surgery" },
  { id: "mo_112", label: "Myringotomy with Grommet Insertion", category: "ENT Surgery" },
  // Ophthalmology
  { id: "mo_113", label: "Cataract Surgery — Phacoemulsification + IOL", category: "Ophthalmology" },
  { id: "mo_114", label: "Glaucoma — Trabeculectomy", category: "Ophthalmology" },
  { id: "mo_115", label: "Vitrectomy — Posterior Segment", category: "Ophthalmology" },
  { id: "mo_116", label: "Retinal Detachment Repair", category: "Ophthalmology" },
  { id: "mo_117", label: "Strabismus / Squint Correction", category: "Ophthalmology" },
  { id: "mo_118", label: "Pterygium Excision + Graft", category: "Ophthalmology" },
  { id: "mo_119", label: "DCR — Dacryocystorhinostomy (Endoscopic)", category: "Ophthalmology" },
  { id: "mo_120", label: "Eyelid Surgery — Ptosis / Entropion / Ectropion", category: "Ophthalmology" },
  { id: "mo_121", label: "Corneal Transplant — PKP / DSAEK", category: "Ophthalmology" },
  // Paediatric
  { id: "mo_122", label: "Herniotomy — Paediatric Inguinal Hernia", category: "Paediatric Surgery" },
  { id: "mo_123", label: "Pyloromyotomy — Ramstedt Procedure", category: "Paediatric Surgery" },
  { id: "mo_124", label: "Intussusception — Air Reduction / Surgery", category: "Paediatric Surgery" },
  { id: "mo_125", label: "Hirschsprung Disease — Pull-Through", category: "Paediatric Surgery" },
  { id: "mo_126", label: "Circumcision — Paediatric", category: "Paediatric Surgery" },
  { id: "mo_127", label: "General Paediatric OT", category: "Paediatric Surgery" },
  // Trauma
  { id: "mo_128", label: "Damage Control Laparotomy", category: "Trauma Surgery" },
  { id: "mo_129", label: "Damage Control Surgery", category: "Trauma Surgery" },
  { id: "mo_130", label: "Fasciotomy — Compartment Syndrome", category: "Trauma Surgery" },
  { id: "mo_131", label: "Traumatic Amputation Management", category: "Trauma Surgery" },
  { id: "mo_132", label: "Chest Wall Trauma — Rib Fixation", category: "Trauma Surgery" },
  { id: "mo_133", label: "Pelvic Packing — Haemorrhage Control", category: "Trauma Surgery" },
  // Endocrine
  { id: "mo_134", label: "Adrenalectomy — Laparoscopic / Open", category: "Endocrine Surgery" },
  { id: "mo_135", label: "Pancreatectomy — Distal / Total", category: "Endocrine Surgery" },
  // Training
  { id: "mo_136", label: "Student Training / Surgical Skills Lab", category: "Training & Documentation" },
  { id: "mo_137", label: "Documentation & Case Recording", category: "Training & Documentation" },
  { id: "mo_138", label: "Custom / Other Procedure", category: "Training & Documentation", custom: true },
];

export const ALL_PROCEDURES = [...AYURVEDA_PROCEDURES, ...MODERN_PROCEDURES];

export function getProceduresByDomain(domain: "ayurveda" | "modern") {
  return domain === "ayurveda" ? AYURVEDA_PROCEDURES : MODERN_PROCEDURES;
}
